version: "3"
services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    ports:
      - 1883:1883
    volumes:
      - ./conf/mosquitto:/mosquitto/config
      - ./data/mosquitto:/var/lib/mosquitto

  # https://www.home-assistant.io/docs/installation/docker/
  # For advanced features, use network_mode: host and remove the "ports" key below.
  home-assistant:
    image: homeassistant/home-assistant:2021.1.5
    ports:
      - 8123:8123
    volumes:
      - ./conf/home-assistant:/config

  fake-devices:
    build: fake-devices/
